### ISSUE TITLE
Version 2.0.1 broken in Thunderbird 102

### ISSUE THREAD

**Issue by jobisoft** [jikamens/remote-content-by-folder#3]
Hi Jonathan,

the version 2.0.1 which is listed on ATN (but not in this repo) is currently broken. Offending line is 

`var {DefaultPreferencesLoader} = ChromeUtils.import(extension.rootURI.resolve("/content/defaultPreferencesLoader.jsm"));`

This is no longer supported in TB102. JSM must be loaded from `chrome://` or `resource://` paths.

We could of course just generate a `chrome://` url for our add-on and use that, but I also would like to point out the possibility to get rid of the preference usage altogether and switch to local storage.

What do you think? I can help with a PR.

**Comment by jikamens** [comment]
Current repo is https://github.com/Extended-Thunder/remote-content-by-folder/.
If you have time to submit a PR (there) to use local storage I'm happy to take it, but (a) if I'm the one fixing it, my first impulse is going to be to just make the current code work with as few changes as possible, and (b) if we are going to migrate to using local storage, we probably need to preserve the prefs loader for long enough to migrate preferences from there to local storage, or people will lose their settings when they get the upgrade that switches to local storage.

**Comment by jobisoft** [comment]
FYI: The add-ons support page entry still points to this repo.

Will do a PR.

**Comment by jikamens** [comment]
>The add-ons support page entry still points to this repo.

Fixed, thanks.
